# Complete command reference — Linux/Ubuntu, Windows, macOS
# Each entry: (command, description)

LINUX = {
    "File Management": [
        ("ls",                          "List directory contents"),
        ("ls -la",                      "List all files with details (hidden too)"),
        ("ls -lh",                      "List with human-readable sizes"),
        ("ls -lt",                      "List sorted by modification time"),
        ("cd <dir>",                    "Change directory"),
        ("cd ..",                       "Go up one level"),
        ("cd ~",                        "Go to home directory"),
        ("cd -",                        "Go to previous directory"),
        ("pwd",                         "Print working directory"),
        ("mkdir <dir>",                 "Create directory"),
        ("mkdir -p a/b/c",              "Create nested directories"),
        ("rmdir <dir>",                 "Remove empty directory"),
        ("rm <file>",                   "Delete file"),
        ("rm -f <file>",                "Force delete without prompt"),
        ("rm -rf <dir>",                "Delete directory and all contents"),
        ("cp <src> <dst>",              "Copy file"),
        ("cp -r <src> <dst>",           "Copy directory recursively"),
        ("cp -p <src> <dst>",           "Copy preserving timestamps/permissions"),
        ("mv <src> <dst>",              "Move or rename file"),
        ("touch <file>",                "Create empty file or update timestamp"),
        ("ln <src> <dst>",              "Create hard link"),
        ("ln -s <target> <link>",       "Create symbolic link"),
        ("readlink <link>",             "Show symlink target"),
        ("cat <file>",                  "Display file content"),
        ("cat <a> <b> > <out>",         "Concatenate files"),
        ("less <file>",                 "Scroll through file (q to quit)"),
        ("more <file>",                 "Page through file"),
        ("head <file>",                 "Show first 10 lines"),
        ("head -n 50 <file>",           "Show first 50 lines"),
        ("tail <file>",                 "Show last 10 lines"),
        ("tail -n 50 <file>",           "Show last 50 lines"),
        ("tail -f <file>",              "Follow file in real-time"),
        ("wc -l <file>",                "Count lines"),
        ("wc -w <file>",                "Count words"),
        ("wc -c <file>",                "Count bytes"),
        ("file <file>",                 "Detect file type"),
        ("stat <file>",                 "Detailed file metadata"),
        ("du -sh <dir>",                "Directory total size"),
        ("du -sh *",                    "Size of every item here"),
        ("du -ah | sort -rh | head",    "Top largest files"),
        ("tree",                        "Show directory tree"),
        ("tree -L 2",                   "Tree limited to 2 levels"),
        ("diff <a> <b>",                "Compare two files"),
        ("diff -u <a> <b>",             "Unified diff format"),
        ("patch < file.patch",          "Apply a patch"),
        ("truncate -s 0 <file>",        "Empty a file"),
        ("shred -u <file>",             "Securely delete file"),
        ("split -b 100M <file> part_",  "Split file into 100MB pieces"),
        ("rename 's/old/new/' *.txt",   "Bulk rename files"),
    ],
    "Text Processing": [
        ("grep 'pattern' <file>",       "Search for pattern in file"),
        ("grep -r 'pattern' <dir>",     "Recursive search in directory"),
        ("grep -i 'pattern' <file>",    "Case-insensitive search"),
        ("grep -n 'pattern' <file>",    "Show matching line numbers"),
        ("grep -v 'pattern' <file>",    "Invert — lines NOT matching"),
        ("grep -c 'pattern' <file>",    "Count matching lines"),
        ("grep -l 'pattern' *",         "List files that match"),
        ("grep -A 3 'pattern' <file>",  "Show 3 lines after match"),
        ("grep -B 3 'pattern' <file>",  "Show 3 lines before match"),
        ("grep -E 'a|b' <file>",        "Extended regex (OR)"),
        ("grep -w 'word' <file>",       "Match whole words only"),
        ("awk '{print $1}' <file>",     "Print first column"),
        ("awk '{print $NF}' <file>",    "Print last column"),
        ("awk -F: '{print $1}' <file>", "Custom delimiter"),
        ("awk 'NR>5' <file>",           "Print from line 6 onwards"),
        ("awk '{sum+=$1} END{print sum}' <file>", "Sum a column"),
        ("sed 's/old/new/' <file>",     "Replace first occurrence per line"),
        ("sed 's/old/new/g' <file>",    "Replace all occurrences"),
        ("sed -i 's/old/new/g' <file>", "Replace in file in-place"),
        ("sed -n '10,20p' <file>",      "Print lines 10 to 20"),
        ("sed '/pattern/d' <file>",     "Delete lines matching pattern"),
        ("cut -d',' -f1,3 <file>",      "Cut columns 1 and 3 (CSV)"),
        ("cut -c1-10 <file>",           "Cut first 10 characters"),
        ("sort <file>",                 "Sort alphabetically"),
        ("sort -r <file>",              "Sort in reverse"),
        ("sort -n <file>",              "Sort numerically"),
        ("sort -k2 <file>",             "Sort by second column"),
        ("sort -u <file>",              "Sort and remove duplicates"),
        ("uniq <file>",                 "Remove consecutive duplicates"),
        ("uniq -c <file>",              "Prefix with occurrence count"),
        ("uniq -d <file>",              "Show only duplicated lines"),
        ("tr 'a-z' 'A-Z'",             "Uppercase all characters"),
        ("tr -d '\\r'",                 "Remove carriage returns"),
        ("tr -s ' '",                   "Squeeze multiple spaces"),
        ("tee <file>",                  "Write to file and stdout"),
        ("xargs rm",                    "Pass stdin as arguments to rm"),
        ("xargs -n 1 curl",             "Run curl for each line"),
        ("paste <a> <b>",              "Merge columns of two files"),
        ("comm <a> <b>",               "Compare sorted files"),
        ("fmt <file>",                  "Reformat paragraph text"),
        ("column -t <file>",            "Format as aligned table"),
        ("nl <file>",                   "Number lines of file"),
        ("strings <binary>",            "Extract readable text from binary"),
        ("od -c <file>",                "Octal dump (show special chars)"),
        ("hexdump -C <file>",           "Hex dump of file"),
    ],
    "Search & Find": [
        ("find . -name '*.log'",                "Find by filename pattern"),
        ("find . -type f",                      "Find files only"),
        ("find . -type d",                      "Find directories only"),
        ("find . -size +100M",                  "Find files over 100MB"),
        ("find . -mtime -7",                    "Modified in last 7 days"),
        ("find . -newer <file>",                "Newer than reference file"),
        ("find . -empty",                       "Find empty files/dirs"),
        ("find . -perm 777",                    "Find by permissions"),
        ("find . -user <user>",                 "Find by owner"),
        ("find . -name '*.py' -delete",         "Find and delete"),
        ("find . -name '*.log' -exec rm {} ;",  "Find and execute"),
        ("find . -name '*.txt' | xargs grep 'pattern'", "Find then grep"),
        ("locate <name>",                       "Fast find by name (uses index)"),
        ("updatedb",                            "Update locate database"),
        ("which <cmd>",                         "Find command in PATH"),
        ("whereis <cmd>",                       "Find binary, man, source"),
        ("type <cmd>",                          "Show how command is interpreted"),
    ],
    "Process Management": [
        ("ps aux",                      "List all running processes"),
        ("ps aux | grep <name>",        "Find process by name"),
        ("ps -ef",                      "Full process list with PPID"),
        ("pstree",                      "Show process tree"),
        ("top",                         "Live process monitor"),
        ("htop",                        "Interactive process viewer (install first)"),
        ("kill <PID>",                  "Send TERM signal to process"),
        ("kill -9 <PID>",              "Force kill (SIGKILL)"),
        ("kill -l",                     "List all signals"),
        ("killall <name>",              "Kill all processes by name"),
        ("pkill <name>",                "Kill by name pattern"),
        ("pkill -u <user>",             "Kill all processes of user"),
        ("pgrep <name>",                "Get PID(s) by name"),
        ("pgrep -a <name>",             "PID with command line"),
        ("jobs",                        "List background jobs"),
        ("fg %1",                       "Bring job 1 to foreground"),
        ("bg %1",                       "Resume job 1 in background"),
        ("cmd &",                       "Run command in background"),
        ("nohup cmd &",                 "Run immune to hangup/logout"),
        ("disown %1",                   "Remove job from shell control"),
        ("nice -n 10 cmd",              "Run with lower priority (10)"),
        ("nice -n -10 cmd",             "Run with higher priority (root)"),
        ("renice 10 -p <PID>",          "Change running process priority"),
        ("lsof",                        "List all open files"),
        ("lsof -p <PID>",              "Files opened by process"),
        ("lsof -i :8080",              "Process using port 8080"),
        ("lsof -u <user>",             "Files opened by user"),
        ("fuser 8080/tcp",              "Who is using port 8080"),
        ("strace -p <PID>",             "Trace system calls of process"),
        ("ltrace cmd",                  "Trace library calls"),
        ("time cmd",                    "Measure execution time"),
        ("timeout 30 cmd",              "Kill if not done in 30 seconds"),
        ("wait",                        "Wait for all background jobs"),
        ("watch -n 2 'ps aux'",         "Re-run command every 2 seconds"),
        ("trap 'cmd' SIGINT",           "Run cmd on Ctrl+C"),
    ],
    "Network": [
        ("ip a",                                "Show all IP addresses"),
        ("ip a show eth0",                      "Show specific interface"),
        ("ip r",                                "Show routing table"),
        ("ip link set eth0 up",                 "Bring interface up"),
        ("ip link set eth0 down",               "Bring interface down"),
        ("ifconfig",                            "Network interfaces (legacy)"),
        ("ping <host>",                         "Test connectivity"),
        ("ping -c 4 <host>",                    "Ping exactly 4 times"),
        ("ping -i 0.2 <host>",                  "Ping every 0.2 seconds"),
        ("traceroute <host>",                   "Trace network path"),
        ("mtr <host>",                          "Continuous traceroute"),
        ("netstat -tuln",                       "Show listening ports"),
        ("netstat -tulnp",                      "Show with process names"),
        ("ss -tuln",                            "Socket stats (faster)"),
        ("ss -tulnp",                           "Sockets with process names"),
        ("ss -s",                               "Socket summary"),
        ("nmap <host>",                         "Scan host for open ports"),
        ("nmap -sV <host>",                     "Scan with service versions"),
        ("nmap -sU <host>",                     "UDP port scan"),
        ("nmap -A <host>",                      "Aggressive scan (OS detect)"),
        ("nmap 192.168.1.0/24",                 "Scan entire subnet"),
        ("curl <url>",                          "Fetch URL content"),
        ("curl -I <url>",                       "Fetch headers only"),
        ("curl -O <url>",                       "Download file"),
        ("curl -L <url>",                       "Follow redirects"),
        ("curl -u user:pass <url>",             "Basic auth"),
        ("curl -X POST -d 'data' <url>",        "POST request"),
        ("curl -H 'Authorization: Bearer tk' <url>", "With auth header"),
        ("curl -k <url>",                       "Skip SSL verification"),
        ("wget <url>",                          "Download file"),
        ("wget -r -l 3 <url>",                  "Recursive download depth 3"),
        ("wget -c <url>",                       "Resume interrupted download"),
        ("ssh user@host",                       "SSH connection"),
        ("ssh -p 2222 user@host",               "SSH on custom port"),
        ("ssh -i ~/.ssh/key.pem user@host",     "SSH with private key"),
        ("ssh -L 8080:localhost:80 user@host",  "Local port forwarding"),
        ("ssh -R 80:localhost:8080 user@host",  "Remote port forwarding"),
        ("ssh-keygen -t ed25519",               "Generate SSH key pair"),
        ("ssh-copy-id user@host",               "Copy SSH key to server"),
        ("scp file user@host:/path/",           "Copy file to remote"),
        ("scp -r dir/ user@host:/path/",        "Copy directory to remote"),
        ("scp user@host:/path/file .",          "Copy file from remote"),
        ("rsync -av src/ dst/",                 "Sync directories"),
        ("rsync -av --delete src/ dst/",        "Sync deleting extras"),
        ("rsync -av -e ssh src/ user@host:/d/", "Remote sync via SSH"),
        ("rsync --progress src/ dst/",          "Show progress"),
        ("dig <domain>",                        "DNS lookup"),
        ("dig <domain> MX",                     "MX records"),
        ("dig +short <domain>",                 "Short DNS answer"),
        ("nslookup <domain>",                   "DNS query (interactive)"),
        ("host <domain>",                       "DNS summary"),
        ("whois <domain>",                      "Domain registration info"),
        ("hostname",                            "Show/set hostname"),
        ("hostname -I",                         "Show all IP addresses"),
        ("arp -a",                              "Show ARP table"),
        ("route -n",                            "Show routing table"),
        ("nc -zv <host> 443",                   "Test port connectivity"),
        ("nc -l 8080",                          "Listen on port 8080"),
        ("nc <host> 8080",                      "Connect to port"),
        ("tcpdump -i eth0",                     "Capture packets on eth0"),
        ("tcpdump -i eth0 port 80",             "Capture HTTP traffic"),
        ("iptables -L",                         "List firewall rules"),
        ("iptables -A INPUT -p tcp --dport 80 -j ACCEPT", "Allow port 80"),
        ("ufw status",                          "UFW firewall status"),
        ("ufw allow 22",                        "Allow SSH"),
        ("ufw deny 23",                         "Block telnet"),
        ("ufw enable",                          "Enable firewall"),
        ("ufw disable",                         "Disable firewall"),
    ],
    "Disk & Storage": [
        ("df -h",                               "Disk space of all filesystems"),
        ("df -hT",                              "Include filesystem type"),
        ("df -h .",                             "Disk space of current filesystem"),
        ("du -sh <dir>",                        "Directory total size"),
        ("du -sh *",                            "Size of each item here"),
        ("du -ah",                              "All files with sizes"),
        ("du -ah | sort -rh | head -20",        "Top 20 largest files"),
        ("ncdu",                                "Interactive disk usage (install first)"),
        ("lsblk",                               "List block devices"),
        ("lsblk -f",                            "Include filesystem info"),
        ("blkid",                               "Block device UUIDs"),
        ("mount",                               "List all mounted filesystems"),
        ("mount /dev/sdb1 /mnt",                "Mount a device"),
        ("mount -o ro /dev/sdb1 /mnt",          "Mount read-only"),
        ("umount /mnt",                         "Unmount device"),
        ("umount -l /mnt",                      "Lazy unmount (when busy)"),
        ("fdisk -l",                            "List all disk partitions"),
        ("fdisk /dev/sdb",                      "Interactive partition editor"),
        ("parted /dev/sdb print",               "Show partition table"),
        ("mkfs.ext4 /dev/sdb1",                "Format as ext4"),
        ("mkfs.xfs /dev/sdb1",                  "Format as XFS"),
        ("mkfs.vfat /dev/sdb1",                 "Format as FAT32"),
        ("fsck /dev/sdb1",                      "Check & repair filesystem"),
        ("e2fsck -f /dev/sdb1",                 "Force ext4 check"),
        ("tune2fs -l /dev/sdb1",               "Show ext4 filesystem info"),
        ("dd if=/dev/sda of=disk.img",          "Clone entire disk to image"),
        ("dd if=/dev/zero of=/dev/sdb bs=4M",   "Wipe disk with zeros"),
        ("dd if=image.iso of=/dev/sdb bs=4M status=progress", "Write ISO to USB"),
        ("sync",                                "Flush filesystem write buffers"),
        ("hdparm -tT /dev/sda",                 "Disk read speed test"),
        ("smartctl -a /dev/sda",               "S.M.A.R.T. disk health"),
        ("lvdisplay",                           "Show LVM logical volumes"),
        ("vgdisplay",                           "Show LVM volume groups"),
        ("pvdisplay",                           "Show LVM physical volumes"),
        ("lvcreate -L 10G -n lv1 vg0",         "Create logical volume"),
        ("lvresize -L +5G /dev/vg0/lv1",       "Extend logical volume"),
        ("swapoff -a",                          "Disable all swap"),
        ("swapon -a",                           "Enable all swap from fstab"),
        ("mkswap /dev/sdb2",                    "Format swap partition"),
        ("swapon /dev/sdb2",                    "Enable swap partition"),
    ],
    "User & Permissions": [
        ("whoami",                              "Print current username"),
        ("id",                                  "Show UID, GID, groups"),
        ("id <user>",                           "Show info for user"),
        ("who",                                 "List logged-in users"),
        ("w",                                   "Who is logged in and doing what"),
        ("last",                                "Login history"),
        ("last -n 20",                          "Last 20 logins"),
        ("lastlog",                             "Most recent login per user"),
        ("groups",                              "Show current user groups"),
        ("groups <user>",                       "Show groups for user"),
        ("sudo cmd",                            "Run command as root"),
        ("sudo -i",                             "Interactive root shell"),
        ("sudo -u <user> cmd",                  "Run as specific user"),
        ("su - <user>",                         "Switch to user (login shell)"),
        ("su -",                                "Switch to root"),
        ("passwd",                              "Change your password"),
        ("passwd <user>",                       "Change another user password (root)"),
        ("passwd -l <user>",                    "Lock user account"),
        ("passwd -u <user>",                    "Unlock user account"),
        ("adduser <name>",                      "Create new user (interactive)"),
        ("useradd -m -s /bin/bash <name>",      "Create user with home + bash"),
        ("usermod -aG sudo <name>",             "Add user to sudo group"),
        ("usermod -aG docker <name>",           "Add user to docker group"),
        ("usermod -l <new> <old>",              "Rename user"),
        ("deluser <name>",                      "Delete user"),
        ("deluser --remove-home <name>",        "Delete user and home dir"),
        ("groupadd <name>",                     "Create new group"),
        ("groupdel <name>",                     "Delete group"),
        ("gpasswd -a <user> <group>",           "Add user to group"),
        ("gpasswd -d <user> <group>",           "Remove user from group"),
        ("chmod 755 <file>",                    "Set rwxr-xr-x"),
        ("chmod 644 <file>",                    "Set rw-r--r--"),
        ("chmod +x <file>",                     "Add execute permission"),
        ("chmod -R 755 <dir>",                  "Recursive permission change"),
        ("chmod u+x,g-w,o-rwx <file>",         "Fine-grained permission change"),
        ("chown user:group <file>",             "Change owner and group"),
        ("chown -R user:group <dir>",           "Recursive ownership change"),
        ("chgrp <group> <file>",               "Change group only"),
        ("umask 022",                           "Default permissions mask"),
        ("umask",                               "Show current umask"),
        ("setfacl -m u:alice:rwx <file>",       "Grant ACL to user alice"),
        ("setfacl -m g:dev:r-- <file>",         "Grant ACL to group dev"),
        ("getfacl <file>",                      "Show ACL entries"),
        ("chattr +i <file>",                    "Make file immutable"),
        ("lsattr <file>",                       "Show file attributes"),
        ("visudo",                              "Safely edit /etc/sudoers"),
        ("cat /etc/passwd",                     "List all user accounts"),
        ("cat /etc/group",                      "List all groups"),
        ("cat /etc/shadow",                     "Hashed passwords (root only)"),
    ],
    "System Info & Monitoring": [
        ("uname -a",                    "Full kernel and system info"),
        ("uname -r",                    "Kernel version only"),
        ("lsb_release -a",              "Linux distribution details"),
        ("cat /etc/os-release",         "OS version file"),
        ("cat /proc/version",           "Kernel build info"),
        ("uptime",                      "How long the system has been running"),
        ("uptime -p",                   "Human-readable uptime"),
        ("date",                        "Current date and time"),
        ("date '+%Y-%m-%d %H:%M:%S'",  "Formatted date"),
        ("timedatectl",                 "Timezone and NTP status"),
        ("timedatectl set-timezone UTC", "Set timezone"),
        ("hwclock",                     "Hardware clock time"),
        ("cal",                         "Current month calendar"),
        ("cal 2025",                    "Full year calendar"),
        ("hostname",                    "Show/set system hostname"),
        ("hostnamectl",                 "Detailed hostname info"),
        ("lscpu",                       "CPU architecture and specs"),
        ("cat /proc/cpuinfo",           "Raw CPU info"),
        ("nproc",                       "Number of CPU cores"),
        ("free -h",                     "RAM and swap usage"),
        ("cat /proc/meminfo",           "Detailed memory info"),
        ("vmstat 1 5",                  "VM stats every 1s, 5 times"),
        ("vmstat -s",                   "Memory statistics summary"),
        ("iostat",                      "CPU and I/O statistics"),
        ("iostat -x 1",                 "Extended I/O stats every 1s"),
        ("sar -u 1 5",                  "CPU usage every 1s (sysstat)"),
        ("sar -r 1 5",                  "Memory usage (sysstat)"),
        ("mpstat",                      "Per-CPU usage stats"),
        ("dstat",                       "Versatile real-time stats"),
        ("lspci",                       "List PCI devices"),
        ("lspci -v",                    "Verbose PCI info"),
        ("lsusb",                       "List USB devices"),
        ("lsusb -t",                    "USB tree"),
        ("lshw",                        "Detailed hardware list"),
        ("dmidecode",                   "BIOS/hardware info (root)"),
        ("dmesg",                       "Kernel ring buffer messages"),
        ("dmesg | tail -20",            "Last 20 kernel messages"),
        ("dmesg -T",                    "With human-readable timestamps"),
        ("dmesg -w",                    "Follow kernel messages"),
        ("journalctl",                  "View systemd journal"),
        ("journalctl -xe",              "Jump to end with explanations"),
        ("journalctl -f",               "Follow journal live"),
        ("journalctl -u ssh",           "Logs for SSH service"),
        ("journalctl --since '1 hour ago'", "Recent logs"),
        ("journalctl --disk-usage",     "How much space logs use"),
        ("env",                         "List all environment variables"),
        ("printenv PATH",               "Print specific variable"),
        ("export VAR=value",            "Set environment variable"),
        ("unset VAR",                   "Remove environment variable"),
        ("echo $VAR",                   "Print variable value"),
        ("history",                     "Command history"),
        ("history | grep git",          "Search command history"),
        ("history -c",                  "Clear history"),
        ("!42",                         "Re-run history entry 42"),
        ("!!",                          "Re-run last command"),
        ("!$",                          "Last argument of previous command"),
        ("alias ll='ls -la'",           "Create command alias"),
        ("unalias ll",                  "Remove alias"),
        ("type <cmd>",                  "How command is resolved"),
        ("hash",                        "List hashed commands"),
        ("ulimit -a",                   "Show resource limits"),
        ("ulimit -n 65535",             "Set open file descriptor limit"),
    ],
    "Services & Scheduling": [
        ("systemctl status <svc>",              "Show service status"),
        ("systemctl start <svc>",               "Start service"),
        ("systemctl stop <svc>",                "Stop service"),
        ("systemctl restart <svc>",             "Restart service"),
        ("systemctl reload <svc>",              "Reload config without restart"),
        ("systemctl enable <svc>",              "Enable service at boot"),
        ("systemctl disable <svc>",             "Disable service at boot"),
        ("systemctl is-active <svc>",           "Check if service is running"),
        ("systemctl is-enabled <svc>",          "Check if enabled at boot"),
        ("systemctl list-units --type=service", "List all services"),
        ("systemctl list-units --failed",       "List failed services"),
        ("systemctl daemon-reload",             "Reload systemd config"),
        ("systemctl mask <svc>",                "Prevent service from starting"),
        ("systemctl unmask <svc>",              "Allow service to start again"),
        ("journalctl -u <svc> -f",              "Follow service logs"),
        ("crontab -e",                          "Edit your cron jobs"),
        ("crontab -l",                          "List your cron jobs"),
        ("crontab -r",                          "Remove all your cron jobs"),
        ("crontab -u <user> -l",               "List another user cron"),
        ("cat /etc/crontab",                    "System-wide cron file"),
        ("ls /etc/cron.d/",                     "Drop-in cron jobs"),
        ("ls /etc/cron.daily/",                 "Daily cron scripts"),
        ("at 10:30",                            "Schedule one-time job at 10:30"),
        ("at now + 1 hour",                     "Run 1 hour from now"),
        ("atq",                                 "List scheduled at jobs"),
        ("atrm <id>",                           "Remove at job by ID"),
        ("batch",                               "Run when load permits"),
    ],
    "Package Management (Ubuntu/Debian)": [
        ("apt update",                  "Refresh package index"),
        ("apt upgrade",                 "Upgrade all upgradable packages"),
        ("apt full-upgrade",            "Upgrade + remove obsolete"),
        ("apt dist-upgrade",            "Smart dependency upgrades"),
        ("apt install <pkg>",           "Install a package"),
        ("apt install <pkg>=<ver>",     "Install specific version"),
        ("apt remove <pkg>",            "Remove package (keep config)"),
        ("apt purge <pkg>",             "Remove package and config files"),
        ("apt autoremove",              "Remove unused dependencies"),
        ("apt clean",                   "Clear downloaded package cache"),
        ("apt autoclean",               "Clear outdated cached packages"),
        ("apt search <term>",           "Search available packages"),
        ("apt show <pkg>",              "Show package details"),
        ("apt list --installed",        "List installed packages"),
        ("apt list --upgradable",       "List upgradable packages"),
        ("apt-mark hold <pkg>",         "Prevent package from upgrading"),
        ("apt-mark unhold <pkg>",       "Allow package to upgrade"),
        ("dpkg -l",                     "List all installed packages"),
        ("dpkg -l | grep <name>",       "Search installed packages"),
        ("dpkg -i <file>.deb",          "Install .deb file"),
        ("dpkg -r <pkg>",               "Remove package via dpkg"),
        ("dpkg -L <pkg>",               "List files owned by package"),
        ("dpkg -S <file>",              "Which package owns a file"),
        ("dpkg --get-selections",       "Export all installed packages"),
        ("snap install <pkg>",          "Install snap package"),
        ("snap install <pkg> --classic","Install classic snap"),
        ("snap list",                   "List installed snaps"),
        ("snap refresh",                "Update all snaps"),
        ("snap remove <pkg>",           "Remove snap"),
        ("flatpak install <pkg>",       "Install flatpak app"),
        ("flatpak list",                "List installed flatpaks"),
        ("flatpak update",              "Update all flatpaks"),
        ("pip install <pkg>",           "Install Python package"),
        ("pip install -r requirements.txt", "Install from requirements"),
        ("pip list",                    "List installed Python packages"),
        ("pip show <pkg>",              "Show Python package info"),
        ("pip upgrade <pkg>",           "Upgrade Python package"),
        ("pip uninstall <pkg>",         "Uninstall Python package"),
        ("npm install -g <pkg>",        "Install Node package globally"),
        ("npm list -g --depth=0",       "List global Node packages"),
        ("npm update -g <pkg>",         "Update global Node package"),
        ("cargo install <pkg>",         "Install Rust package"),
    ],
    "Archive & Compression": [
        ("tar -cvf archive.tar dir/",       "Create tar archive"),
        ("tar -xvf archive.tar",            "Extract tar archive"),
        ("tar -tvf archive.tar",            "List tar contents"),
        ("tar -cvzf archive.tar.gz dir/",   "Create gzip archive"),
        ("tar -xvzf archive.tar.gz",        "Extract gzip archive"),
        ("tar -xvzf archive.tar.gz -C /dest/", "Extract to directory"),
        ("tar -cvjf archive.tar.bz2 dir/",  "Create bzip2 archive"),
        ("tar -xvjf archive.tar.bz2",       "Extract bzip2 archive"),
        ("tar -cvJf archive.tar.xz dir/",   "Create xz archive"),
        ("tar -xvJf archive.tar.xz",        "Extract xz archive"),
        ("tar --exclude='*.log' -cvzf a.tgz dir/", "Exclude pattern"),
        ("gzip <file>",                     "Compress file with gzip"),
        ("gzip -9 <file>",                  "Maximum gzip compression"),
        ("gzip -d <file>.gz",               "Decompress gzip"),
        ("gunzip <file>.gz",                "Decompress gzip (alias)"),
        ("zcat <file>.gz",                  "View gzip without extracting"),
        ("bzip2 <file>",                    "Compress with bzip2"),
        ("bunzip2 <file>.bz2",              "Decompress bzip2"),
        ("xz <file>",                       "Compress with xz"),
        ("unxz <file>.xz",                  "Decompress xz"),
        ("zip archive.zip file1 file2",     "Create zip"),
        ("zip -r archive.zip dir/",         "Zip directory recursively"),
        ("zip -9 archive.zip dir/",         "Maximum zip compression"),
        ("zip -e archive.zip file",         "Encrypted zip"),
        ("unzip archive.zip",               "Extract zip"),
        ("unzip archive.zip -d /dest/",     "Extract to directory"),
        ("unzip -l archive.zip",            "List zip contents"),
        ("unzip -t archive.zip",            "Test zip integrity"),
        ("7z a archive.7z dir/",            "Create 7z archive"),
        ("7z x archive.7z",                 "Extract 7z archive"),
        ("7z l archive.7z",                 "List 7z contents"),
        ("7z t archive.7z",                 "Test 7z integrity"),
        ("rar a archive.rar dir/",          "Create rar archive"),
        ("unrar x archive.rar",             "Extract rar archive"),
        ("zstd <file>",                     "Compress with zstd"),
        ("zstd -d <file>.zst",              "Decompress zstd"),
    ],
    "Git": [
        ("git init",                        "Initialize new repository"),
        ("git init --bare",                 "Init bare repository (server)"),
        ("git clone <url>",                 "Clone repository"),
        ("git clone --depth 1 <url>",       "Shallow clone (faster)"),
        ("git status",                      "Working tree status"),
        ("git status -s",                   "Short status format"),
        ("git add <file>",                  "Stage specific file"),
        ("git add .",                       "Stage all changes"),
        ("git add -p",                      "Interactively stage hunks"),
        ("git add -u",                      "Stage modified+deleted (not new)"),
        ("git commit -m 'message'",         "Commit with message"),
        ("git commit --amend",              "Amend last commit"),
        ("git commit --amend --no-edit",    "Amend without changing message"),
        ("git push",                        "Push to default remote"),
        ("git push -u origin main",         "Push and set upstream"),
        ("git push --force-with-lease",     "Safer force push"),
        ("git pull",                        "Fetch and merge"),
        ("git pull --rebase",               "Fetch and rebase"),
        ("git fetch",                       "Download without merging"),
        ("git fetch --all",                 "Fetch all remotes"),
        ("git branch",                      "List local branches"),
        ("git branch -a",                   "List all branches (incl remote)"),
        ("git branch <name>",               "Create new branch"),
        ("git branch -d <name>",            "Delete merged branch"),
        ("git branch -D <name>",            "Force delete branch"),
        ("git branch -m <old> <new>",       "Rename branch"),
        ("git checkout <branch>",           "Switch to branch"),
        ("git checkout -b <branch>",        "Create and switch to branch"),
        ("git switch <branch>",             "Switch branch (newer syntax)"),
        ("git switch -c <branch>",          "Create and switch (newer)"),
        ("git merge <branch>",              "Merge branch into current"),
        ("git merge --no-ff <branch>",      "Merge with merge commit"),
        ("git merge --squash <branch>",     "Squash all commits into one"),
        ("git rebase <branch>",             "Rebase current onto branch"),
        ("git rebase -i HEAD~3",            "Interactive rebase last 3"),
        ("git rebase --abort",              "Abort rebase"),
        ("git rebase --continue",           "Continue after conflict"),
        ("git cherry-pick <hash>",          "Apply specific commit"),
        ("git log",                         "Full commit history"),
        ("git log --oneline",               "Compact one-line log"),
        ("git log --graph --oneline",       "Visual branch graph"),
        ("git log -p",                      "Log with diffs"),
        ("git log --author='Name'",         "Filter by author"),
        ("git log --since='2 weeks ago'",   "Filter by date"),
        ("git log <file>",                  "Commits affecting file"),
        ("git show <hash>",                 "Show commit details"),
        ("git blame <file>",                "Who changed each line"),
        ("git diff",                        "Unstaged changes"),
        ("git diff --staged",               "Staged changes"),
        ("git diff HEAD",                   "All uncommitted changes"),
        ("git diff <branch1>..<branch2>",   "Diff between branches"),
        ("git stash",                       "Stash current changes"),
        ("git stash push -m 'name'",        "Named stash"),
        ("git stash list",                  "List stashes"),
        ("git stash pop",                   "Apply and remove last stash"),
        ("git stash apply stash@{1}",       "Apply specific stash"),
        ("git stash drop stash@{0}",        "Delete a stash"),
        ("git stash clear",                 "Delete all stashes"),
        ("git reset HEAD~1",                "Undo last commit (keep changes)"),
        ("git reset --hard HEAD~1",         "Undo and discard changes"),
        ("git reset HEAD <file>",           "Unstage file"),
        ("git revert <hash>",               "Create revert commit"),
        ("git restore <file>",              "Discard working tree changes"),
        ("git restore --staged <file>",     "Unstage file"),
        ("git tag v1.0",                    "Lightweight tag"),
        ("git tag -a v1.0 -m 'msg'",       "Annotated tag"),
        ("git push origin v1.0",            "Push specific tag"),
        ("git push origin --tags",          "Push all tags"),
        ("git remote -v",                   "List remotes"),
        ("git remote add origin <url>",     "Add remote"),
        ("git remote set-url origin <url>", "Change remote URL"),
        ("git remote remove <name>",        "Remove remote"),
        ("git submodule add <url>",         "Add submodule"),
        ("git submodule update --init",     "Init/update submodules"),
        ("git clean -fd",                   "Remove untracked files/dirs"),
        ("git bisect start",                "Start bisect session"),
        ("git bisect good <hash>",          "Mark commit as good"),
        ("git bisect bad",                  "Mark current as bad"),
        ("git reflog",                      "History of HEAD movements"),
        ("git shortlog -sn",                "Commits per author"),
        ("git archive --format=zip HEAD > out.zip", "Export repo as zip"),
    ],
    "Docker": [
        ("docker ps",                               "List running containers"),
        ("docker ps -a",                            "List all containers"),
        ("docker ps -q",                            "List only container IDs"),
        ("docker images",                           "List local images"),
        ("docker images -a",                        "List all images"),
        ("docker pull <image>",                     "Pull image from registry"),
        ("docker pull <image>:<tag>",               "Pull specific version"),
        ("docker push <image>",                     "Push image to registry"),
        ("docker run <image>",                      "Create and start container"),
        ("docker run -it <image> bash",             "Interactive shell"),
        ("docker run -d <image>",                   "Run detached"),
        ("docker run -p 8080:80 <image>",           "Map host:container port"),
        ("docker run -v /host:/container <image>",  "Mount volume"),
        ("docker run --name myapp <image>",         "Named container"),
        ("docker run --rm <image>",                 "Remove when stopped"),
        ("docker run -e KEY=val <image>",           "Set environment variable"),
        ("docker run --network host <image>",       "Use host networking"),
        ("docker start <id>",                       "Start stopped container"),
        ("docker stop <id>",                        "Gracefully stop container"),
        ("docker kill <id>",                        "Force kill container"),
        ("docker restart <id>",                     "Restart container"),
        ("docker rm <id>",                          "Remove container"),
        ("docker rm -f <id>",                       "Force remove running"),
        ("docker rmi <image>",                      "Remove image"),
        ("docker rmi -f <image>",                   "Force remove image"),
        ("docker build -t name:tag .",              "Build image from Dockerfile"),
        ("docker build --no-cache -t name .",       "Build without cache"),
        ("docker exec -it <id> bash",               "Shell into container"),
        ("docker exec <id> cmd",                    "Run command in container"),
        ("docker logs <id>",                        "Container log output"),
        ("docker logs -f <id>",                     "Follow live logs"),
        ("docker logs --tail 100 <id>",             "Last 100 log lines"),
        ("docker inspect <id>",                     "Detailed container info"),
        ("docker stats",                            "Live resource usage"),
        ("docker top <id>",                         "Processes in container"),
        ("docker cp <id>:/path ./local",            "Copy from container"),
        ("docker cp ./local <id>:/path",            "Copy to container"),
        ("docker commit <id> name:tag",             "Create image from container"),
        ("docker tag <image> new:tag",              "Tag image"),
        ("docker save -o file.tar <image>",         "Export image to tar"),
        ("docker load -i file.tar",                 "Import image from tar"),
        ("docker volume ls",                        "List volumes"),
        ("docker volume create <name>",             "Create volume"),
        ("docker volume rm <name>",                 "Remove volume"),
        ("docker volume inspect <name>",            "Volume details"),
        ("docker network ls",                       "List networks"),
        ("docker network create <name>",            "Create network"),
        ("docker network rm <name>",                "Remove network"),
        ("docker network inspect <name>",           "Network details"),
        ("docker compose up",                       "Start compose services"),
        ("docker compose up -d",                    "Start detached"),
        ("docker compose down",                     "Stop and remove"),
        ("docker compose down -v",                  "Also remove volumes"),
        ("docker compose ps",                       "List compose services"),
        ("docker compose logs -f",                  "Follow compose logs"),
        ("docker compose build",                    "Build compose images"),
        ("docker compose pull",                     "Pull compose images"),
        ("docker compose restart <svc>",            "Restart specific service"),
        ("docker system prune",                     "Remove all unused resources"),
        ("docker system prune -a",                  "Remove all including images"),
        ("docker system df",                        "Docker disk usage"),
    ],
    "Shell & Scripting": [
        ("echo 'text'",                     "Print text"),
        ("echo -e 'line1\\nline2'",         "Print with escape sequences"),
        ("printf '%s\\n' 'text'",           "Formatted print"),
        ("read VAR",                        "Read input into variable"),
        ("read -p 'Enter: ' VAR",           "Read with prompt"),
        ("read -s VAR",                     "Read silently (passwords)"),
        ("if [ cond ]; then ... fi",        "if/then/fi block"),
        ("[ -f <file> ]",                   "Test file exists"),
        ("[ -d <dir> ]",                    "Test directory exists"),
        ("[ -z $VAR ]",                     "Test string is empty"),
        ("[ -n $VAR ]",                     "Test string is non-empty"),
        ("[ $a -eq $b ]",                   "Test integers equal"),
        ("[ $a -gt $b ]",                   "Test a greater than b"),
        ("for i in 1 2 3; do ... done",     "for loop"),
        ("for f in *.txt; do ... done",     "Loop over files"),
        ("while [ cond ]; do ... done",     "while loop"),
        ("case $VAR in a) ;; b) ;; esac",   "case statement"),
        ("func() { ...; }",                 "Define function"),
        ("source <script>",                 "Run script in current shell"),
        (". <script>",                      "Source script (short form)"),
        ("bash -x script.sh",               "Debug script"),
        ("bash -n script.sh",               "Check syntax without running"),
        ("set -e",                          "Exit on any error"),
        ("set -u",                          "Error on undefined variable"),
        ("set -o pipefail",                 "Fail if any pipe cmd fails"),
        ("trap 'cleanup' EXIT",             "Run on script exit"),
        ("$$",                              "Current process PID"),
        ("$?",                              "Exit code of last command"),
        ("$#",                              "Number of script arguments"),
        ("$@",                              "All arguments as list"),
        ("$1 $2 ...",                       "Positional arguments"),
        ("${VAR:-default}",                 "Variable with default"),
        ("${#VAR}",                         "Length of variable"),
        ("${VAR/old/new}",                  "Replace in variable"),
        ("$(cmd)",                          "Command substitution"),
        ("$((1 + 2))",                      "Arithmetic expansion"),
        ("cmd1 && cmd2",                    "Run cmd2 if cmd1 succeeds"),
        ("cmd1 || cmd2",                    "Run cmd2 if cmd1 fails"),
        ("cmd1 ; cmd2",                     "Run both regardless"),
        ("cmd1 | cmd2",                     "Pipe output to cmd2"),
        ("cmd > file",                      "Redirect stdout to file"),
        ("cmd >> file",                     "Append stdout to file"),
        ("cmd 2> error.log",                "Redirect stderr"),
        ("cmd &> all.log",                  "Redirect both stdout+stderr"),
        ("cmd < file",                      "Use file as stdin"),
        ("cmd 2>&1 | other",                "Pipe stdout and stderr"),
    ],
}

WINDOWS = {
    "CMD — File Management": [
        ("dir",                             "List directory contents"),
        ("dir /a",                          "List including hidden files"),
        ("dir /s /b",                       "Recursive bare listing"),
        ("dir /o:d",                        "Sort by date"),
        ("cd <dir>",                        "Change directory"),
        ("cd ..",                           "Go up one level"),
        ("cd /",                            "Go to root of drive"),
        ("cd /d D:\\path",                  "Change drive and directory"),
        ("mkdir <dir>",                     "Create directory"),
        ("mkdir a\\b\\c",                   "Create nested directories"),
        ("rmdir <dir>",                     "Remove empty directory"),
        ("rmdir /s /q <dir>",               "Remove directory and contents"),
        ("del <file>",                      "Delete file"),
        ("del /f /q <file>",               "Force delete without prompt"),
        ("del /s *.tmp",                    "Delete all .tmp files"),
        ("copy <src> <dst>",                "Copy file"),
        ("copy /b <src> <dst>",             "Binary copy"),
        ("xcopy <src> <dst> /e /h /k",      "Copy directory recursively"),
        ("robocopy <src> <dst>",            "Robust file copy"),
        ("robocopy <src> <dst> /mir",       "Mirror (sync) directories"),
        ("move <src> <dst>",                "Move file or directory"),
        ("rename <old> <new>",              "Rename file"),
        ("ren <old> <new>",                 "Rename (short form)"),
        ("type <file>",                     "Display file content"),
        ("more <file>",                     "Page through file"),
        ("attrib +h <file>",                "Set hidden attribute"),
        ("attrib -h <file>",                "Remove hidden attribute"),
        ("attrib +r <file>",                "Set read-only attribute"),
        ("icacls <file>",                   "Show file permissions"),
        ("icacls <file> /grant User:F",     "Grant full control to User"),
        ("mklink <link> <target>",          "Create symbolic link"),
        ("mklink /d <link> <target>",       "Create directory symlink"),
        ("compact /c <file>",               "Compress file (NTFS)"),
        ("compact /u <file>",               "Uncompress file (NTFS)"),
        ("fc <a> <b>",                      "Compare two files"),
        ("findstr 'pattern' <file>",        "Search text in file"),
        ("findstr /r /s 'pattern' *",       "Recursive regex search"),
        ("tree",                            "Show directory tree"),
        ("tree /f",                         "Tree with file names"),
        ("pushd <dir>",                     "Save current dir, go to new"),
        ("popd",                            "Return to saved directory"),
        ("assoc .txt",                      "Show file association"),
        ("ftype txtfile",                   "Show file type handler"),
    ],
    "CMD — Process & System": [
        ("tasklist",                        "List running processes"),
        ("tasklist /fi 'imagename eq n.exe'","Filter by process name"),
        ("taskkill /im <name>.exe",         "Kill process by name"),
        ("taskkill /pid <PID>",             "Kill process by PID"),
        ("taskkill /f /im <name>.exe",      "Force kill process"),
        ("start <program>",                 "Start program"),
        ("start /b <program>",              "Start in background"),
        ("start /wait <program>",           "Wait for program to finish"),
        ("runas /user:Administrator cmd",   "Run as administrator"),
        ("sc query",                        "List all services"),
        ("sc query <name>",                 "Service status"),
        ("sc start <name>",                 "Start service"),
        ("sc stop <name>",                  "Stop service"),
        ("sc config <name> start=auto",     "Set service to auto-start"),
        ("net start <name>",                "Start service"),
        ("net stop <name>",                 "Stop service"),
        ("net start",                       "List running services"),
        ("schtasks /query",                 "List scheduled tasks"),
        ("schtasks /create ...",            "Create scheduled task"),
        ("schtasks /delete /tn 'name'",     "Delete scheduled task"),
        ("at 14:00 <program>",             "Schedule one-time task"),
        ("shutdown /s /t 0",               "Shutdown immediately"),
        ("shutdown /r /t 0",               "Restart immediately"),
        ("shutdown /l",                    "Log off current user"),
        ("shutdown /a",                    "Abort scheduled shutdown"),
        ("msconfig",                        "System configuration (GUI)"),
        ("taskmgr",                         "Open Task Manager (GUI)"),
        ("services.msc",                    "Services manager (GUI)"),
        ("eventvwr",                        "Event Viewer (GUI)"),
        ("perfmon",                         "Performance monitor (GUI)"),
        ("resmon",                          "Resource monitor (GUI)"),
        ("wmic cpu get name",               "CPU model name"),
        ("wmic memorychip get capacity",    "RAM capacity"),
        ("wmic os get caption",             "Windows version"),
        ("wmic process list brief",         "Process list"),
        ("wmic product get name",           "List installed software"),
    ],
    "CMD — Network": [
        ("ipconfig",                        "Show IP configuration"),
        ("ipconfig /all",                   "Full network info"),
        ("ipconfig /release",               "Release DHCP address"),
        ("ipconfig /renew",                 "Renew DHCP address"),
        ("ipconfig /flushdns",              "Clear DNS cache"),
        ("ipconfig /displaydns",            "Show DNS cache"),
        ("ping <host>",                     "Test connectivity"),
        ("ping -t <host>",                  "Continuous ping"),
        ("ping -n 10 <host>",               "Ping 10 times"),
        ("ping -l 1000 <host>",             "Ping with 1000 byte packet"),
        ("tracert <host>",                  "Trace route to host"),
        ("tracert -d <host>",               "Trace without DNS resolution"),
        ("pathping <host>",                 "Combined ping+tracert"),
        ("netstat -an",                     "All connections and ports"),
        ("netstat -b",                      "Show process for each conn"),
        ("netstat -r",                      "Routing table"),
        ("nslookup <domain>",               "DNS lookup"),
        ("nslookup <domain> 8.8.8.8",      "DNS via specific server"),
        ("arp -a",                          "Show ARP table"),
        ("arp -d *",                        "Clear ARP cache"),
        ("route print",                     "Print routing table"),
        ("route add <dest> mask <mask> <gw>","Add route"),
        ("netsh wlan show profiles",        "List saved WiFi networks"),
        ("netsh wlan show profile name='X' key=clear", "Show WiFi password"),
        ("netsh interface ip set address 'Ethernet' dhcp", "Set to DHCP"),
        ("netsh firewall show state",       "Firewall status"),
        ("netsh advfirewall set allprofiles state off", "Disable firewall"),
        ("telnet <host> <port>",            "Test TCP connection"),
        ("curl <url>",                      "Fetch URL (Win10+)"),
        ("curl -O <url>",                   "Download file"),
    ],
    "CMD — Disk & User": [
        ("diskpart",                        "Interactive disk partitioner"),
        ("chkdsk C:",                       "Check disk for errors"),
        ("chkdsk C: /f",                    "Fix disk errors"),
        ("chkdsk C: /r",                    "Repair bad sectors"),
        ("format D: /fs:NTFS",              "Format drive as NTFS"),
        ("vol C:",                          "Show volume label"),
        ("label C: MyDrive",                "Set volume label"),
        ("defrag C: /u /v",                 "Defragment and show progress"),
        ("compact /s /a",                   "Show compression state"),
        ("cipher /e /s:<dir>",              "Encrypt directory (EFS)"),
        ("fsutil volume diskfree C:",       "Free space on C:"),
        ("net user",                        "List local users"),
        ("net user <name>",                 "Show user details"),
        ("net user <name> <pass> /add",     "Create user"),
        ("net user <name> /delete",         "Delete user"),
        ("net user <name> /active:no",      "Disable user account"),
        ("net localgroup",                  "List local groups"),
        ("net localgroup Administrators <u> /add", "Add to admin group"),
        ("whoami",                          "Current user"),
        ("whoami /groups",                  "Current user's groups"),
        ("whoami /priv",                    "Current privileges"),
        ("gpupdate /force",                 "Force Group Policy update"),
        ("gpresult /r",                     "Show applied GP settings"),
    ],
    "CMD — Variables & Misc": [
        ("set",                             "List all environment variables"),
        ("set VAR=value",                   "Set variable (session only)"),
        ("setx VAR value",                  "Set variable permanently"),
        ("setx VAR value /m",               "Set system-wide variable"),
        ("echo %VAR%",                      "Print variable value"),
        ("echo %PATH%",                     "Print PATH"),
        ("echo %USERNAME%",                 "Current username"),
        ("echo %COMPUTERNAME%",             "Computer name"),
        ("echo %DATE%",                     "Current date"),
        ("echo %TIME%",                     "Current time"),
        ("set VAR=",                        "Delete variable"),
        ("cls",                             "Clear screen"),
        ("ver",                             "Windows version"),
        ("systeminfo",                      "Full system information"),
        ("date",                            "Show/set date"),
        ("time",                            "Show/set time"),
        ("hostname",                        "Computer hostname"),
        ("clip",                            "Copy stdin to clipboard"),
        ("type file | clip",                "Copy file to clipboard"),
        ("where <cmd>",                     "Find command location in PATH"),
        ("help <cmd>",                      "Command help"),
        ("<cmd> /?",                        "Command help (alt)"),
        ("doskey /history",                 "Command history"),
        ("reg query HKLM\\Software",        "Query registry key"),
        ("reg add HKCU\\...",               "Add registry value"),
        ("reg delete HKCU\\...",            "Delete registry key"),
        ("regedit",                         "Registry Editor (GUI)"),
        ("msiexec /i <file>.msi",           "Install MSI package"),
        ("msiexec /x <file>.msi",           "Uninstall MSI package"),
        ("winget search <app>",             "Search for app (winget)"),
        ("winget install <id>",             "Install app via winget"),
        ("winget upgrade --all",            "Upgrade all apps"),
        ("winget uninstall <id>",           "Uninstall app"),
        ("winget list",                     "List installed apps"),
        ("powershell -Command '...'",       "Run PowerShell command"),
        ("powershell -File script.ps1",     "Run PowerShell script"),
        ("wsl",                             "Open WSL shell"),
        ("wsl --list",                      "List WSL distributions"),
        ("wsl --install",                   "Install WSL"),
    ],
    "PowerShell — Files": [
        ("Get-ChildItem",                           "List files (alias: ls, dir)"),
        ("Get-ChildItem -Hidden",                   "Include hidden files"),
        ("Get-ChildItem -Recurse",                  "Recursive listing"),
        ("Get-ChildItem -Filter *.txt",             "Filter by extension"),
        ("Set-Location <path>",                     "Change directory (alias: cd)"),
        ("Get-Location",                            "Print directory (alias: pwd)"),
        ("New-Item <name> -ItemType File",          "Create file"),
        ("New-Item <name> -ItemType Directory",     "Create directory"),
        ("Remove-Item <file>",                      "Delete file"),
        ("Remove-Item <dir> -Recurse -Force",       "Delete directory"),
        ("Copy-Item <src> <dst>",                   "Copy file"),
        ("Copy-Item <src> <dst> -Recurse",          "Copy directory"),
        ("Move-Item <src> <dst>",                   "Move/rename"),
        ("Get-Content <file>",                      "Read file (alias: cat)"),
        ("Get-Content <file> -Tail 20",             "Last 20 lines"),
        ("Get-Content <file> -Wait",                "Follow file (tail -f)"),
        ("Set-Content <file> 'text'",               "Write to file"),
        ("Add-Content <file> 'text'",               "Append to file"),
        ("Out-File <file>",                         "Redirect output to file"),
        ("Select-String 'pattern' <file>",          "Search in file (grep)"),
        ("Get-Item <file>",                         "Get file/dir object"),
        ("Test-Path <path>",                        "Check if path exists"),
        ("Resolve-Path <path>",                     "Get absolute path"),
        ("Rename-Item <old> <new>",                 "Rename item"),
        ("New-Item -ItemType SymbolicLink -Name <link> -Target <target>", "Create symlink"),
        ("Compress-Archive <src> <dst>.zip",        "Create zip archive"),
        ("Expand-Archive <zip> <dst>",              "Extract zip archive"),
        ("Get-FileHash <file>",                     "Get file hash (SHA256)"),
        ("Get-FileHash <file> -Algorithm MD5",      "Get MD5 hash"),
    ],
    "PowerShell — Process & Network": [
        ("Get-Process",                         "List running processes"),
        ("Get-Process <name>",                  "Find process by name"),
        ("Stop-Process -Name <name>",           "Kill process by name"),
        ("Stop-Process -Id <PID>",              "Kill process by PID"),
        ("Stop-Process -Name <name> -Force",    "Force kill"),
        ("Start-Process <app>",                 "Start application"),
        ("Start-Process <app> -Verb RunAs",     "Run as administrator"),
        ("Get-Service",                         "List all services"),
        ("Get-Service <name>",                  "Get specific service"),
        ("Start-Service <name>",                "Start service"),
        ("Stop-Service <name>",                 "Stop service"),
        ("Restart-Service <name>",              "Restart service"),
        ("Set-Service <name> -StartupType Automatic", "Auto-start service"),
        ("Get-EventLog -LogName System -Newest 20", "System event log"),
        ("Invoke-WebRequest <url>",             "HTTP request (alias: curl, wget)"),
        ("Invoke-WebRequest <url> -OutFile f",  "Download file"),
        ("Invoke-RestMethod <url>",             "REST API call"),
        ("Test-NetConnection <host> -Port 80",  "Test TCP connection"),
        ("Test-NetConnection <host>",           "Ping host"),
        ("Resolve-DnsName <domain>",            "DNS lookup"),
        ("Get-NetAdapter",                      "List network adapters"),
        ("Get-NetIPAddress",                    "List IP addresses"),
        ("Get-NetRoute",                        "Show routing table"),
        ("Get-NetTCPConnection",                "List TCP connections"),
        ("Get-NetTCPConnection -LocalPort 80",  "Who uses port 80"),
    ],
    "PowerShell — System": [
        ("Get-ComputerInfo",                    "Full system information"),
        ("Get-Date",                            "Current date and time"),
        ("Get-Date -Format 'yyyy-MM-dd'",       "Formatted date"),
        ("Get-Host",                            "PowerShell host info"),
        ("$PSVersionTable",                     "PowerShell version"),
        ("Get-ExecutionPolicy",                 "Current execution policy"),
        ("Set-ExecutionPolicy RemoteSigned",    "Allow local scripts"),
        ("Get-Hotfix",                          "List installed Windows updates"),
        ("Get-Hotfix -Id KB<num>",              "Check specific update"),
        ("Get-Volume",                          "Disk volumes and space"),
        ("Get-Disk",                            "Physical disks"),
        ("Get-Partition",                       "Disk partitions"),
        ("Get-WmiObject Win32_BIOS",            "BIOS information"),
        ("Get-WmiObject Win32_Processor",       "CPU information"),
        ("Get-WmiObject Win32_PhysicalMemory",  "RAM information"),
        ("Get-History",                         "Command history"),
        ("Clear-History",                       "Clear command history"),
        ("Get-Alias",                           "List all aliases"),
        ("New-Alias myalias cmd",               "Create alias"),
        ("Get-Module -ListAvailable",           "List available modules"),
        ("Install-Module <name>",               "Install PowerShell module"),
        ("Import-Module <name>",                "Load module"),
        ("Get-Command",                         "List all commands"),
        ("Get-Command -Name *net*",             "Find commands matching net"),
        ("Get-Help <cmd>",                      "Command help"),
        ("Get-Help <cmd> -Examples",            "Show examples"),
        ("Write-Host 'text'",                   "Print to console"),
        ("Write-Output 'text'",                 "Send to pipeline"),
        ("Read-Host 'Prompt'",                  "Read user input"),
        ("$env:PATH",                           "Show PATH variable"),
        ("$env:PATH += ';C:\\new\\path'",       "Add to PATH (session)"),
        ("Restart-Computer",                    "Restart computer"),
        ("Stop-Computer",                       "Shutdown computer"),
    ],
}

MAC = {
    "File Management": [
        ("ls",                              "List directory contents"),
        ("ls -la",                          "List all with details"),
        ("ls -lh",                          "Human-readable sizes"),
        ("ls -lt",                          "Sort by modification time"),
        ("ls -G",                           "Colorized output"),
        ("cd <dir>",                        "Change directory"),
        ("cd ~",                            "Go to home directory"),
        ("pwd",                             "Print working directory"),
        ("mkdir <dir>",                     "Create directory"),
        ("mkdir -p a/b/c",                  "Create nested directories"),
        ("rm <file>",                       "Delete file"),
        ("rm -rf <dir>",                    "Delete directory recursively"),
        ("cp <src> <dst>",                  "Copy file"),
        ("cp -r <src> <dst>",               "Copy directory"),
        ("mv <src> <dst>",                  "Move or rename"),
        ("touch <file>",                    "Create file / update timestamp"),
        ("ln -s <target> <link>",           "Create symbolic link"),
        ("cat <file>",                      "Display file content"),
        ("less <file>",                     "Page through file"),
        ("head -n 20 <file>",               "First 20 lines"),
        ("tail -n 20 <file>",               "Last 20 lines"),
        ("tail -f <file>",                  "Follow file live"),
        ("open <file>",                     "Open with default app"),
        ("open -a 'App Name' <file>",       "Open with specific app"),
        ("open .",                          "Open current dir in Finder"),
        ("open -R <file>",                  "Reveal file in Finder"),
        ("open -n -a Terminal",             "Open new Terminal window"),
        ("du -sh <dir>",                    "Directory size"),
        ("du -sh *",                        "Size of all items"),
        ("find . -name '*.log'",            "Find files by name"),
        ("find . -type f -mtime -7",        "Files modified in last 7 days"),
        ("mdfind <term>",                   "Spotlight search (fast)"),
        ("mdfind -name <name>",             "Spotlight search by filename"),
        ("mdls <file>",                     "Spotlight metadata for file"),
        ("diff <a> <b>",                    "Compare two files"),
        ("file <file>",                     "Detect file type"),
        ("stat -f '%z bytes' <file>",       "File size in bytes (BSD stat)"),
        ("wc -l <file>",                    "Count lines"),
        ("tree",                            "Directory tree (install first)"),
        ("lsof +D <dir>",                   "Files open in directory"),
    ],
    "Mac Specific": [
        ("open <url>",                              "Open URL in default browser"),
        ("open -a Safari <url>",                    "Open URL in Safari"),
        ("pbcopy < <file>",                         "Copy file content to clipboard"),
        ("pbpaste",                                 "Paste from clipboard"),
        ("echo 'text' | pbcopy",                    "Copy text to clipboard"),
        ("pbpaste > <file>",                        "Paste clipboard to file"),
        ("say 'Hello World'",                       "Text to speech"),
        ("say -v 'Alex' 'Hello'",                   "Specific voice"),
        ("caffeinate",                              "Prevent sleep"),
        ("caffeinate -t 3600",                      "Prevent sleep for 1 hour"),
        ("caffeinate -i cmd",                       "Prevent sleep during command"),
        ("defaults read com.apple.dock",            "Read Dock defaults"),
        ("defaults write com.apple.dock autohide -bool true", "Auto-hide Dock"),
        ("killall Dock",                            "Restart Dock"),
        ("killall Finder",                          "Restart Finder"),
        ("defaults write NSGlobalDomain AppleShowAllExtensions -bool true", "Show all extensions"),
        ("osascript -e 'display alert \"Hello\"'",  "AppleScript alert"),
        ("osascript -e 'set volume 5'",             "Set volume (0-7)"),
        ("screencapture screen.png",                "Capture full screen"),
        ("screencapture -w <file>",                 "Capture window"),
        ("screencapture -R x,y,w,h <file>",         "Capture region"),
        ("sw_vers",                                 "macOS version info"),
        ("sw_vers -productVersion",                 "macOS version number"),
        ("system_profiler SPHardwareDataType",       "Hardware info"),
        ("system_profiler SPSoftwareDataType",       "Software info"),
        ("diskutil list",                           "List disks"),
        ("diskutil info /dev/disk0",                "Disk info"),
        ("diskutil eraseDisk APFS MyDisk /dev/disk2","Erase and format disk"),
        ("diskutil mount /dev/disk2s1",             "Mount volume"),
        ("diskutil unmount /dev/disk2s1",           "Unmount volume"),
        ("diskutil verifyVolume /",                 "Verify root volume"),
        ("diskutil repairVolume /",                 "Repair root volume"),
        ("launchctl list",                          "List launch agents"),
        ("launchctl load ~/Library/LaunchAgents/x.plist", "Load agent"),
        ("launchctl unload ~/Library/LaunchAgents/x.plist", "Unload agent"),
        ("launchctl start <label>",                 "Start service"),
        ("launchctl stop <label>",                  "Stop service"),
        ("airport -s",                              "Scan WiFi networks"),
        ("airport -I",                              "Current WiFi info"),
        ("networksetup -listallnetworkservices",     "List network services"),
        ("networksetup -getinfo Ethernet",          "Ethernet network info"),
        ("networksetup -setdhcp Ethernet",          "Set Ethernet to DHCP"),
        ("scutil --get ComputerName",               "Get computer name"),
        ("scutil --set ComputerName 'NewName'",     "Set computer name"),
        ("spctl --status",                          "Gatekeeper status"),
        ("spctl --master-disable",                  "Disable Gatekeeper (caution)"),
        ("codesign -dv --verbose=4 <app>",          "Show code signature"),
        ("xattr -l <file>",                         "List extended attributes"),
        ("xattr -d com.apple.quarantine <file>",    "Remove quarantine flag"),
        ("xcode-select --install",                  "Install Xcode tools"),
        ("xcode-select -p",                         "Show Xcode path"),
        ("security list-keychains",                 "List keychains"),
        ("security find-internet-password -l <site>","Find internet password"),
        ("pmset -g",                                "Power management settings"),
        ("pmset sleepnow",                          "Sleep immediately"),
        ("shutdown -r now",                         "Restart immediately"),
        ("shutdown -h now",                         "Shutdown immediately"),
        ("sips -z 500 500 <image>",                 "Resize image"),
        ("sips -s format png <file>.jpg --out out.png", "Convert image format"),
        ("qlmanage -p <file>",                      "Quick Look preview"),
        ("mdutil -s /",                             "Spotlight index status"),
        ("mdutil -E /",                             "Rebuild Spotlight index"),
        ("dscl . list /Users",                      "List all users"),
        ("dscl . read /Users/<name>",               "Read user record"),
        ("dscl . -create /Users/<name>",            "Create user entry"),
    ],
    "Homebrew": [
        ("brew install <pkg>",              "Install package"),
        ("brew install --cask <app>",       "Install GUI app"),
        ("brew uninstall <pkg>",            "Remove package"),
        ("brew uninstall --cask <app>",     "Remove GUI app"),
        ("brew update",                     "Update Homebrew"),
        ("brew upgrade",                    "Upgrade all packages"),
        ("brew upgrade <pkg>",              "Upgrade specific package"),
        ("brew search <term>",              "Search packages"),
        ("brew info <pkg>",                 "Package info"),
        ("brew list",                       "List installed packages"),
        ("brew list --cask",                "List installed casks"),
        ("brew outdated",                   "List outdated packages"),
        ("brew pin <pkg>",                  "Prevent package from upgrading"),
        ("brew unpin <pkg>",                "Allow package to upgrade"),
        ("brew doctor",                     "Check for issues"),
        ("brew cleanup",                    "Remove old versions"),
        ("brew deps <pkg>",                 "Show package dependencies"),
        ("brew uses --installed <pkg>",     "What depends on package"),
        ("brew services list",              "List brew-managed services"),
        ("brew services start <svc>",       "Start brew service"),
        ("brew services stop <svc>",        "Stop brew service"),
        ("brew services restart <svc>",     "Restart brew service"),
        ("brew tap <user>/<repo>",          "Add third-party tap"),
        ("brew tap",                        "List taps"),
        ("brew untap <user>/<repo>",        "Remove tap"),
    ],
    "Network": [
        ("ifconfig",                        "Show network interfaces"),
        ("ifconfig en0",                    "Show specific interface"),
        ("ping <host>",                     "Test connectivity"),
        ("ping -c 4 <host>",                "Ping 4 times"),
        ("traceroute <host>",               "Trace route"),
        ("mtr <host>",                      "Continuous traceroute"),
        ("netstat -an",                     "Active connections"),
        ("netstat -tuln",                   "Listening ports"),
        ("lsof -i :8080",                  "Who uses port 8080"),
        ("lsof -i TCP",                     "All TCP connections"),
        ("ss -tuln",                        "Socket stats (if installed)"),
        ("nmap <host>",                     "Port scan"),
        ("curl <url>",                      "Fetch URL"),
        ("curl -O <url>",                   "Download file"),
        ("curl -I <url>",                   "HTTP headers only"),
        ("wget <url>",                      "Download file"),
        ("ssh user@host",                   "SSH connection"),
        ("scp file user@host:/path/",       "Copy to remote"),
        ("rsync -av src/ dst/",             "Sync directories"),
        ("dig <domain>",                    "DNS lookup"),
        ("nslookup <domain>",               "DNS query"),
        ("host <domain>",                   "DNS summary"),
        ("whois <domain>",                  "Domain info"),
        ("nc -zv <host> 443",               "Test port connectivity"),
        ("arp -a",                          "Show ARP table"),
        ("route -n get default",            "Show default gateway"),
        ("networksetup -getdnsservers Wi-Fi", "DNS servers for WiFi"),
    ],
    "Process & System": [
        ("ps aux",                          "List all processes"),
        ("ps aux | grep <name>",            "Find process by name"),
        ("top",                             "Live process monitor"),
        ("htop",                            "Interactive monitor (brew install)"),
        ("kill <PID>",                      "Kill process"),
        ("kill -9 <PID>",                  "Force kill"),
        ("killall <name>",                  "Kill by name"),
        ("pgrep <name>",                    "Get PID by name"),
        ("lsof -p <PID>",                  "Files opened by process"),
        ("activity monitor",                "Open Activity Monitor (GUI)"),
        ("vm_stat",                         "Virtual memory stats"),
        ("sysctl -a",                       "Kernel parameters"),
        ("sysctl hw.physmem",               "Physical memory"),
        ("sysctl hw.ncpu",                  "Number of CPUs"),
        ("uname -a",                        "System/kernel info"),
        ("uptime",                          "System uptime"),
        ("who",                             "Logged-in users"),
        ("last",                            "Login history"),
        ("sudo -i",                         "Root shell"),
        ("sudo -l",                         "List sudo privileges"),
        ("su - <user>",                     "Switch user"),
        ("passwd",                          "Change password"),
        ("dscacheutil -q user",             "List users (directory)"),
        ("systemsetup -getusingnetworktime", "NTP status"),
        ("date",                            "Current date/time"),
        ("date '+%Y-%m-%d'",               "Formatted date"),
        ("cal",                             "Calendar"),
        ("env",                             "Environment variables"),
        ("export VAR=value",               "Set variable"),
        ("history",                         "Command history"),
        ("sudo reboot",                     "Restart"),
        ("sudo shutdown -h now",            "Shutdown"),
        ("sudo shutdown -r +10",            "Restart in 10 minutes"),
    ],
    "Package Management": [
        ("brew install <pkg>",              "Install via Homebrew"),
        ("pip3 install <pkg>",              "Install Python 3 package"),
        ("pip3 install -r requirements.txt","Install from requirements"),
        ("pip3 list",                       "List Python packages"),
        ("npm install -g <pkg>",            "Install Node package globally"),
        ("gem install <pkg>",               "Install Ruby gem"),
        ("gem list",                        "List installed gems"),
        ("pod install",                     "Install CocoaPods"),
        ("cargo install <pkg>",             "Install Rust package"),
        ("composer require <pkg>",          "Install PHP package"),
        ("go install <pkg>",                "Install Go package"),
        ("mas search <app>",                "Search Mac App Store (mas tool)"),
        ("mas install <id>",                "Install from App Store"),
        ("mas upgrade",                     "Upgrade App Store apps"),
        ("mas list",                        "List App Store apps"),
    ],
    "Archive & Compression": [
        ("tar -cvzf archive.tar.gz dir/",   "Create gzip archive"),
        ("tar -xvzf archive.tar.gz",        "Extract gzip archive"),
        ("tar -cvjf archive.tar.bz2 dir/",  "Create bzip2 archive"),
        ("tar -xvjf archive.tar.bz2",       "Extract bzip2 archive"),
        ("zip -r archive.zip dir/",         "Create zip"),
        ("unzip archive.zip",               "Extract zip"),
        ("unzip -l archive.zip",            "List zip contents"),
        ("ditto -ck --rsrc src dst.zip",    "Create zip with resource forks"),
        ("ditto -xk src.zip dst/",          "Extract zip (ditto)"),
        ("gzip <file>",                     "Compress with gzip"),
        ("gunzip <file>.gz",                "Decompress gzip"),
        ("compress <file>",                 "BSD compress"),
        ("uncompress <file>.Z",             "BSD uncompress"),
    ],
    "Git": [
        ("git init",                        "Initialize repository"),
        ("git clone <url>",                 "Clone repository"),
        ("git status",                      "Working tree status"),
        ("git add .",                       "Stage all changes"),
        ("git commit -m 'msg'",             "Commit"),
        ("git push",                        "Push to remote"),
        ("git pull",                        "Pull from remote"),
        ("git branch",                      "List branches"),
        ("git checkout -b <branch>",        "Create and switch branch"),
        ("git merge <branch>",              "Merge branch"),
        ("git log --oneline --graph",       "Visual history"),
        ("git stash",                       "Stash changes"),
        ("git stash pop",                   "Apply stash"),
        ("git diff",                        "Unstaged changes"),
        ("git diff --staged",               "Staged changes"),
        ("git reset HEAD~1",                "Undo last commit"),
        ("git revert <hash>",               "Revert commit"),
        ("git tag v1.0",                    "Create tag"),
        ("git remote -v",                   "List remotes"),
        ("git blame <file>",                "Who changed each line"),
        ("git clean -fd",                   "Remove untracked files"),
        ("git reflog",                      "History of HEAD"),
    ],
}

OS_LABELS = {
    "linux":   "Linux / Ubuntu",
    "windows": "Windows (CMD + PowerShell)",
    "mac":     "macOS",
}

ALL = {
    "linux":   LINUX,
    "windows": WINDOWS,
    "mac":     MAC,
}
